### ISSUE TITLE
Forenkle menyen/navigasjonen til "Oppgaver" og "Ansatte"

### ISSUE THREAD

**Issue by magnedavidsen** [blankoslo/Trak#22]
...la resten være filter/valg inne på visningen

**Comment by Zenjjim** [comment]
Design forslag for issue:
![image](https://user-images.githubusercontent.com/23628986/135445936-8af858fd-e0ff-4536-88d7-242f25716b2b.png)
![image](https://user-images.githubusercontent.com/23628986/135445984-5632c88a-5081-4d3f-b759-95f2239f9dda.png)
