### ISSUE TITLE
Mobiltilpasning

### ISSUE THREAD

**Issue by magnedavidsen** [blankoslo/Trak#24]

**Comment by Zenjjim** [comment]
# Ansatte:
![Ansatte - Mobil](https://user-images.githubusercontent.com/23628986/135458270-e89abf5d-4546-4cb5-93d3-6881c4a649f3.png)
![Ansatte - Mobil - Filter](https://user-images.githubusercontent.com/23628986/135458265-53a4565f-6fb6-40c9-a57e-e05f40a19d98.png)
# Ansatt side:
![Ansattside - Mobil](https://user-images.githubusercontent.com/23628986/135458273-bb61b430-41ef-47ac-acd6-ff233ff0a8bb.png)
![Ansattside - Mobil - Historikk](https://user-images.githubusercontent.com/23628986/135458272-85cfbb72-2099-48e2-bbcb-92219ced1c53.png)
# Oppgaver
![Oppgaver - Mobil](https://user-images.githubusercontent.com/23628986/135458275-fe5b80db-0ecf-4473-b602-1b3d3cd62c32.png)
![Oppgaver- Mobil - Filter](https://user-images.githubusercontent.com/23628986/135458276-7905ef4b-2b1d-4406-b033-49208263b9c6.png)

**Comment by Zenjjim** [comment]
Mal:
![Prossmal - Mobil](https://user-images.githubusercontent.com/23628986/135463794-a8eab754-6dea-4c6a-b339-9ff80ae7a0f2.png)
