### ISSUE TITLE
Oppdatering av faser/oppgaver ved endring i oppstartsdato/termineringsdato

### ISSUE THREAD

**Issue by maxschau** [blankoslo/Trak#52]
Dersom en av disse to datoene blir forandret bør vi ha en funksjon i cron/phases som oppdaterer fasene/oppgavene i henholdsvis onboarding eller offboarding for den ansatte.

**Comment by Zenjjim** [comment]
Her kan en ide være å kanskje lagre oppstart og oppsigleses dato også sammenligne dette med blank sin. Om det er et avvik så oppdateres oppgavene knyttet til denne datoen?

Ex: oppstart endres fra 1.1 til 1.2. Da vil cron jobben se at datoen er endret, enten slette også opprette nye oppstarteoppgaver eller endte de eksisterende oppgaven med ny dato. Her tror jeg det letteste vil være å slette og lage nye mtp at oppstart kan potensielt utsettes med et halvt år og nye oppgaver har blitt opprettet i den tidsperioden

**Comment by maxschau** [comment]
> Her kan en ide være å kanskje lagre oppstart og oppsigleses dato også sammenligne dette med blank sin. Om det er et avvik så oppdateres oppgavene knyttet til denne datoen?
> 
> Ex: oppstart endres fra 1.1 til 1.2. Da vil cron jobben se at datoen er endret, enten slette også opprette nye oppstarteoppgaver eller endte de eksisterende oppgaven med ny dato. Her tror jeg det letteste vil være å slette og lage nye mtp at oppstart kan potensielt utsettes med et halvt år og nye oppgaver har blitt opprettet i den tidsperioden

Akkurat det jeg har tenkt også
