### ISSUE TITLE
Skrive om notifikasjonslogikk

### ISSUE THREAD

**Issue by maxschau** [blankoslo/Trak#71]
- Ansatte som har oppgaver som forfaller skal få varsel om de ønsker
- Det vil si at selv ansatte som ikke har direkte personalansvar skal fortsatt få varsel så lenge de har oppgaver de er ansvarlige for

**Comment by Zenjjim** [comment]
Her ønsker jeg også at det blir gjort endring i databasen slik at listen med notifikasjonsvalg blir gjort om til flere boolske verdier slik det er gjort med slack valg
